travis:
  secure:
    BINSTAR_TOKEN: D6KeKkvcgXQNHFGdj6I4a7DFIKH1AsQZpEYXlV+qVBNdweWmrE6nO349yh8Sm37liFs6Jgxtu/38bc2d4ydZ4xj0ZfNdSzTM9HZtgDaUj+S09xJICW4RWNZuRQ/X1AhbuuDJ7ao13pTGnyAGBbmbeadyGNP0/piFTx2KzlmrButCLAoEM5+qSuza+Bidzc4jJ0trRwcOn8UsiKrxgukDbhbVwfrQRJ8Cnftht4YZ7Ol7uMkCJhQHH80MaH6LQ+l3hUx7a4rsVxQCFYBcuxENd8ILwBnC4nSD5RpmPo8mui7oXduNRD1ryXt1+xJjam7dRxMR1NO/NBDF3C2QnhjTNvprBa3KYvf8Kq9BMVVLgD+dUEX0RzFgr/2DejKJvZ3FvgXQkh3xZh6AIRz7MMn3bg8XwRWeg4vGzSYtGmliqNHGeLVjQlFBP6XEmn7ZwrBL9I7OdjzkiLe7+tCPhTk6XHp/ULikVWk5BJo2nIGv5snxr9Q/NUkMhjntDvpyMx6LSGsyQnbHYrBfS9mw/Ln7XYCGsXjbUAIdXLYNq1oTffTmlmZMc/5pyFtuMwd7jagWtUjN7eYcyoqqISFQd2QIiReqkmO33Ns5NQpaTlSV9t1deskPhscFSFGxzNolqC5wsuE4jBSXWHuQYTJ1kliy9PCUgQtI9a2624Gf1EF/+oY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
